
services:
    symfony.cmf.core.pathMapper:
        class: Symfony\Cmf\Bundle\CoreBundle\Helper\DirectPathMapper
        arguments:
            basepath: %symfony.cmf.mainmenu_basepath%
        shared: true

    symfony.cmf.core.fileHelper:
        class: Symfony\Cmf\Bundle\CoreBundle\Helper\RepositoryFileHelper
        arguments:
            loader: @jackalope.loader
            pathPrefix: %symfony.cmf.content_basepath%
            fileBasePath: %symfony.cmf.filestore_basepath%
            fileRelativePath: %symfony.cmf.filestore_relative_basepath%
