language: php

php:
    - 5.3
    - 5.4
    - 5.5

env:
  - SYMFONY_VERSION=2.4.*

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=dev-master
  include:
    - php: 5.5
      env: SYMFONY_VERSION=2.3.*
    - php: 5.5
      env: SYMFONY_VERSION=dev-master

before_script:
  - composer self-update
  - composer require symfony/symfony:${SYMFONY_VERSION} --prefer-source
  # this should not be needed, but travis ends up with an unhealthy mix between phpunit 3 and 4
  - wget https://phar.phpunit.de/phpunit-lts.phar

script: ./phpunit-lts.phar --coverage-text

notifications:
  irc: "irc.freenode.org#symfony-cmf"
  email: "symfony-cmf-devs@googlegroups.com"
